name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-k8s-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: .*|image: soumyahe/pyapp:${{ github.run_number }}|g" k8s/app/deployment.yaml

      - name: Commit changes
        run: |
          git config user.name "Soumya Hegde"
          git config user.email "soumyahegde94@gmail.com"
          git add k8s/app/deployment.yaml
          git commit -m "Update image to ${{ github.run_number }}" || echo "No changes"
          git push
