name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
    # Run SCA and Safety checks
  sca_safety:
    name: SCA and Safety
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Dependencies and safety
        run: |
            if [ -f "app/requirements.txt" ]; then
              python -m pip install --upgrade pip
              pip install safety
              pip install -r app/requirements.txt
            else
              echo "No requirements.txt found, skipping dependency installation."
            fi
     
      
      - name: Run Safety Check
        run: |
            if [ -f "app/requirements.txt" ]; then
                safety check --file=app/requirements.txt --json > safety-report.json || echo "Safety scan completed with issues"
            else
               echo "{}" > safety-report.json
            fi

      - name: Upload Safety Report
        uses: actions/upload-artifact@v4
        with:
          name: safety-scan-report
          path: safety-report.json

    # Run SAST with Bandit       
  sast_bandit:
    name: SAST with Bandit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Bandit
        run: |
            python -m pip install --upgrade pip
            pip install bandit

      - name: Run Bandit SAST Scan
        run: |
            bandit -r app/ -f json -o bandit-report.json || echo "Bandit scan completed with issues"

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-scan-report
          path: bandit-report.json   
   
  
  # secret detection using gitleaks
  secret_detection:
    name: Secret Detection with Gitleaks
    runs-on: ubuntu-latest
   
    permissions:
     contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate secret detection

      - name: Scan for secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
  
   
          
   # Build Docker and pushe to dockerhub
  docker_build:
     name: Build and Push Docker Image
     runs-on: ubuntu-latest
     needs: [sca_safety, sast_bandit, secret_detection]

     steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
         context: app
         file: app/Dockerfile
         push: true
         tags: |
            soumyahe/pyapp:${{ github.run_number }}
            soumyahe/pyapp:latest
         cache-from: type=gha
         cache-to: type=gha,mode=max


   # DAST with OWASP ZAP
  dast_zap:
    name: DAST with OWASP ZAP
    runs-on: ubuntu-latest
    needs: [sca_safety, sast_bandit, secret_detection, docker_build]

    
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull Image
        run: docker pull soumyahe/pyapp:${{ github.run_number }}

      - name: Run App Container
        run: docker run -d --name app -p 8000:8000 soumyahe/pyapp:${{ github.run_number }}

      - name: Wait for App 
        run: |
          echo "Waiting for app to be up..."
          for i in {1..20}; do
            if curl -s http://localhost:8000/ > /dev/null; then
              echo "App is up."
              exit 0
            fi
            echo "Attempt $i: App not up yet."
            sleep 5  
            
          done
          echo "App failed to start"
          docker logs app
          exit 1
          

      - name: Setup and Run OWASP ZAP
        run: |
          mkdir -p zap-reports

          docker run --rm \
            --network host \
            -v $(pwd)/zap-reports:/zap/wrk/:rw \
            owasp/zap2docker-stable \
            zap-full-scan.py \
            -t http://localhost:8000 \
            -r zap-report.html \
            -J zap-report.json \
            -m 5 \
            -a
        
      # Cleanup container (always runs)
      - name: Cleanup Docker Container
        if: always()
        run: |
          docker stop app || true
          docker rm app || true